[Icon Theme]
Name=Pixcons
Comment=16 by 16 pixel art icons layered on top of Breeze Dark
Inherits=breeze-dark,breeze,hicolor
Example=folder
Directories=scalable/apps,scalable/places,scalable/mimetypes,scalable/categories,scalable/devices

[scalable/apps]
Size=16
Type=Scalable
MinSize=8
MaxSize=512
Context=Applications

[scalable/places]
Size=16
Type=Scalable
MinSize=8
MaxSize=512
Context=Places

[scalable/mimetypes]
Size=16
Type=Scalable
MinSize=8
MaxSize=512
Context=MimeTypes

[scalable/categories]
Size=16
Type=Scalable
MinSize=8
MaxSize=512
Context=Categories

[scalable/devices]
Size=16
Type=Scalable
MinSize=8
MaxSize=512
Context=Devices
